# Generated by Django 4.2.14 on 2026-07-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_nomor', models.CharField(max_length=20, unique=True)),
                ('merk', models.CharField(max_length=100)),
                ('model_mobil', models.CharField(max_length=100)),
                ('tahun', models.PositiveIntegerField()),
                ('warna', models.CharField(max_length=50)),
                ('harga_sewa_harian', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('disewa', 'Disewa'), ('maintenance', 'Maintenance')], default='tersedia', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
