# Generated by Django 4.2.14 on 2026-07-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('customers', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_rencana_selesai', models.DateField()),
                ('tanggal_kembali_aktual', models.DateField(blank=True, null=True)),
                ('harga_sewa_harian_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_biaya', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('denda_keterlambatan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('berjalan', 'Berjalan'), ('selesai', 'Selesai')], default='berjalan', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='cars.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='customers.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='drivers.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
