# Generated by Django 4.2.14 on 2026-07-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('no_sim', models.CharField(max_length=32, unique=True)),
                ('no_telepon', models.CharField(max_length=20)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('bertugas', 'Bertugas'), ('nonaktif', 'Nonaktif')], default='tersedia', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
